// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeek2xweXeTigCz-OCP9dqW247MGRQ0_0',
    appId: '1:808030484032:web:54650e97609baeb88451a5',
    messagingSenderId: '808030484032',
    projectId: 'wardrobe-a6e55',
    authDomain: 'wardrobe-a6e55.firebaseapp.com',
    storageBucket: 'wardrobe-a6e55.appspot.com',
    measurementId: 'G-X6QHDWZWMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5R2UUjuYE1mCazqAe9_Ay583DoO99wJY',
    appId: '1:808030484032:android:46589deb725b6bf28451a5',
    messagingSenderId: '808030484032',
    projectId: 'wardrobe-a6e55',
    storageBucket: 'wardrobe-a6e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMP982lpG45jfEu8qxXcKwOrkInXwq2nA',
    appId: '1:808030484032:ios:b0eb92f55ee5b74f8451a5',
    messagingSenderId: '808030484032',
    projectId: 'wardrobe-a6e55',
    storageBucket: 'wardrobe-a6e55.appspot.com',
    iosBundleId: 'com.example.demoProoject1',
  );

}